### ISSUE TITLE
parse_statement_node incompatible with get_policies_for_principal after AWS IAM refactor

### ISSUE THREAD

**Issue by achantavy** [cartography-cncf/cartography#1918]
### Expected behavior
After the AWS IAM refactor in commit 94be56be, `parse_statement_node` should work with the new data format returned by `get_policies_for_principal`. The AWS IAM sync should complete without crashing.

### Actual behavior
`parse_statement_node` crashes with `AttributeError: 'dict' object has no attribute '_properties'` because it was never updated to work with the new data format introduced by the AWS IAM refactor.

### To Reproduce
This integration bug was introduced in commit 94be56be (refactor(aws): Refactor AWS IAM (#1710)) on September 16, 2025.

**What changed:**
- **Before**: `get_policies_for_principal` used `neo4j_session.run()` which returned Neo4j result objects where `r["statements"]` contained Neo4j node objects
- **After**: `get_policies_for_principal` uses `neo4j_session.execute_read(read_list_of_dicts_tx, ...)` which returns dictionaries where `r["statements"]` contains plain Python dictionaries

**The bug**: `parse_statement_node` was never updated to handle the new data format.

**To reproduce:**
1. Run Cartography sync with AWS IAM data that includes assume role relationships
2. The error occurs in `sync_assumerole_relationships` when calling `get_policies_for_principal`
3. Alternatively, reproduce with this unit test:

```python
from cartography.intel.aws import permission_relationships

def test_reproduce_integration_bug():
    # This is the new data format from read_list_of_dicts_tx
(post-refactor)
    statements_from_refactored_code = [
        {
            "action": ["s3:GetObject"],
            "resource": ["arn:aws:s3:::test-bucket/*"],
            "effect": "Allow"
        }
    ]

    # This will raise: AttributeError: 'dict' object has no attribute
'_properties'
    result = permission_relationships.parse_statement_node(statements_
from_refactored_code)
```

## Logs

The full stack trace from the sync error:

```
[2025-09-17T13:29:42Z] ERROR sync.1758110731449-1e50cf99: Error during
 Cartography sync: Traceback (most recent call last):
  File "/app/app/sync.py", line 818, in run_sync
    result = future.result()
  File "/usr/local/lib/python3.13/concurrent/futures/_base.py", line
449, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/concurrent/futures/_base.py", line
401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line
59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/app/sync.py", line 341, in wrapper
    return fn(*args, **kwargs)
  File "/app/app/sync.py", line 778, in sync_account
    _sync_one_account(
    ~~~~~~~~~~~~~~~~~^
        neo4j_session=neo4j_session,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
        aws_requested_syncs=aws_resource_functions,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/app/.venv/lib/python3.13/site-packages/cartography/intel/aws/
__init__.py", line 79, in _sync_one_account
    RESOURCE_FUNCTIONS[func_name](**sync_args)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.13/site-packages/cartography/util.py",
line 205, in timed
    return method(*args, **kwargs)
  File "/app/.venv/lib/python3.13/site-packages/cartography/intel/aws/
iam.py", line 1315, in sync
    sync_assumerole_relationships(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        neo4j_session,
        ^^^^^^^^^^^^^^
    ...<2 lines>...
        common_job_parameters,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/app/.venv/lib/python3.13/site-packages/cartography/util.py",
line 205, in timed
    return method(*args, **kwargs)
  File "/app/.venv/lib/python3.13/site-packages/cartography/intel/aws/
iam.py", line 627, in sync_assumerole_relationships
    policies = get_policies_for_principal(neo4j_session, source_arn)
  File "/app/.venv/lib/python3.13/site-packages/cartography/util.py",
line 205, in timed
    return method(*args, **kwargs)
  File "/app/.venv/lib/python3.13/site-packages/cartography/intel/aws/
iam.py", line 392, in get_policies_for_principal
    policies = {r["policy_id"]: parse_statement_node(r["statements"])
for r in results}
                                ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.13/site-packages/cartography/intel/aws/
permission_relationships.py", line 222, in parse_statement_node
    return [n._properties for n in node_group]
            ^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute '_properties'
```

Please complete the following information:

- Cartography release version or commit hash: 36354afb (current master, includes the problematic refactor 94be56be)

### Additional context

Root Cause: This is an integration bug introduced by the AWS IAM refactor in commit 94be56be. The refactor modernized get_policies_for_principal to use the new read_list_of_dicts_tx pattern but didn't update the downstream parse_statement_node function to handle the new data format.

Specific change that caused the bug:
# Before (working):
```python
- results = neo4j_session.run(get_policy_query, Arn=principal_arn)
```

# After (broken):
```python
+ results = neo4j_session.execute_read(read_list_of_dicts_tx, get_policy_query, Arn=principal_arn)
```

Why this wasn't caught:
- Unit tests for parse_statement_node likely only test it in isolation with mock Neo4j nodes
- Integration tests cover the code path from IAM --> permission_relationships, but the relevant section may have been mocked out (need to validate)
- The refactor was large and this dependency relationship was easy to miss

Suggested Fix: parse_statement_node was made before cartography had client functions. We now have `read_list_of_dict_tx` and can use that or similar instead.
